server:
  servlet:
    context-path: /auth
  port: 20000


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/auth?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 192.168.131.150
    port: 6379
  thymeleaf:
    cache: false
jasypt:
  encryptor:
    password: abc123

mybatis:
  init:
    databaseType: mysql
    databaseSchemaUpdate: false
  type-aliases-package: com.fui.cloud.model
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:conf/log4j2.xml